### ISSUE TITLE
Catalogue reload error

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#12]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Catalogue Detail in Company settings

**General Description/Overview:**

![12](https://user-images.githubusercontent.com/89504119/130951672-4ed982d0-ebbd-44a4-91fd-11c76aad7374.png)

- Scenario :
- EMpty cache and hard reload the page

**List of Steps:**
- [] Even when we empty cache and do hard reload on the page, the page must load
- [] Dont use anything from cache service all modules variable

**Test Criteria:**
- [] Page loading when we navigate through list layout and when we reload the page

**Comment by apriya22** [comment]
* not able to able replicate the issue on prod and local.

![Screenshot from 2021-08-31 09-59-32](https://user-images.githubusercontent.com/89504219/131447694-7c2745e9-0f26-45d2-b768-6e6e7facbc39.png)
![Screenshot from 2021-08-31 11-02-16](https://user-images.githubusercontent.com/89504219/131447713-90b6fa03-3e50-4b91-82a9-ff93a139611c.png)
![Screenshot from 2021-08-31 11-03-36](https://user-images.githubusercontent.com/89504219/131447729-5d854edc-a532-4d28-a9af-6dc79735864c.png)

**Comment by unagireddy** [comment]
1.go to module on sidebar.click on tickets
2.go to forms and then select service catalogues
3. go to new in service catalogue
4. enter requried data and save it
5. go to company settings in sidebar.go to catalogues,click on new
6. enter requried data  and select module as ticket and select the form 
7. and then save 
8. no error observed

**Comment by unagireddy** [comment]
issue is not replicated

1.go to module on sidebar.click on tickets
2.go to forms and then select service catalogues
3. go to new in service catalogue
4. enter requried data and save it
5. go to company settings in sidebar.go to catalogues,click on new
6. enter requried data and select module as ticket and select the form
7. and then save
8. no error observed

**Comment by unagireddy** [comment]
issue is not getting replicated .  kindly follow the steps below

1.go to module on sidebar.click on tickets
2.go to forms and then select service catalogues
3. go to new in service catalogue
4. enter requried data and save it
5. go to company settings in sidebar.go to catalogues,click on new
6. enter requried data and select module as ticket and select the form
7. and then save
8. no error observed

**Comment by karthikbalu1** [comment]
Since the issue is already fixed and not replicated, the issue will be closed.
