### ISSUE TITLE
Remove unwanted tickets search field filters

### ISSUE THREAD

**Issue by phaneendraar** [SubscribeIT/ngDesk#130]
**Owner:** @phaneendraar  

**Task Type:** 
- [ ] New 
- [ ] Improvement 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- render-list-new component

**General Description/Overview:**
We want the fields that dont make sense to end user removed
![image](https://user-images.githubusercontent.com/89504442/131610879-d89e2856-383a-4973-8525-9a9da474b980.png)
![image](https://user-images.githubusercontent.com/89504442/131610899-dc418175-bcba-48c7-9f47-32d4b229649e.png)

**List of Steps:**
- [x] Filter out in the UI to show fields exuding the ones mentioned 

**Test Criteria:**
- [x] male sure the fields mentioned won't show up in the list
- [x] filter and search work as usual

**Comment by kkumar1995** [comment]
**completed**

* Removed Channel,Effective to,Effective from,Post Id,Data ID from  search bar in render list layout
* Tested and screen shots updated in MR

**TODO**
* None
