### ISSUE TITLE
populate channels on search

### ISSUE THREAD

**Issue by phaneendraar** [SubscribeIT/ngDesk#138]
**Owner:** @phaneendraar  

**Task Type:** 
- [ ] New 
- [ ] Improvement 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- render-list-new component

**General Description/Overview:**
We want to have channels being supported on search
Users should see channel name as the list to pick, but in the query it should be sent as ID, refer to requestor on tickets

**List of Steps:**
- [x] get channels working as a filter

**Test Criteria:**
- [x] make sure search by channel works
- [x] filter and search work as usual

**Comment by kkumar1995** [comment]
**completed**

* Debugged the issue & wrote logic for populating values of channels
* values are populating but getting like object object

**TODO**

* Need to fix above issue and need to fix search values of channels
* Testing

**Comment by kkumar1995** [comment]
issue is fixed and Tested

**Comment by phaneendraar** [comment]
Search isn't seem to be working

**Comment by kkumar1995** [comment]
issue is fixed & Tested and test cases updated in MR
