### ISSUE TITLE
Tickets bug - internal error if size more than 16 mb

### ISSUE THREAD

**Issue by phaneendraar** [SubscribeIT/ngDesk#139]
**Owner:** @phaneendraar  

**Task Type:** 
- [ ] New 
- [ ] Improvement 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Data-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**
- ngDesk-Data-Service

**General Description/Overview:**
whenever a ticket payload is more than 16 mb the  server throws internal error as below

org.bson.BsonMaximumSizeExceededException: Payload document size is larger than maximum of 16777216. at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:68) at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:145) at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138) at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59) at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:247) at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) at 
.
.
.
This is because  MongoDB has a 16MB document size limit. See https://docs.mongodb.com/manual/core/document/#document-size-limit for more details.

So instead of 500 error which user cant understand we need to throw 400 and tell user the limit of 16 mb has been exceeded

**List of Steps:**
- [ ] create a payload of 16mb size to replicate issue
- [ ] handle it as 400 error instead of 500 

**Test Criteria:**
- [ ] make sure it sends 400 if payload is more than 16mb with a valid error message

**Comment by spdhage** [comment]
This **issue** is **fixed**
