### ISSUE TITLE
Add validation for the nested relationship in list layouts

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#145]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Module Service
**Components/Services Affected (Ex. Login Component, POST Data API):**
- Layout Service / List layout service

**General Description/Overview:**

As a User, I want to validate the relationship so that There will not be any error while rendering list layout.

**List of Steps:**
- [ ] Write validation in list layout post and put api calls
- [ ] Add a new function / modify existing function which will validate the relationship

**Test Criteria:**
- [ ] Bad request exception thrown if the field is not present

**Comment by CHINMAYJAIN03** [comment]
Added the validation for nested relationship

![Screenshot from 2021-09-07 16-34-35](https://user-images.githubusercontent.com/89504211/132334984-5dfe939a-7755-41f2-9d84-a4793646daf5.png)
![Screenshot from 2021-09-07 16-34-29](https://user-images.githubusercontent.com/89504211/132334991-5554ecf3-8b2a-4e43-a613-85661886b29c.png)
![Screenshot from 2021-09-07 16-34-26](https://user-images.githubusercontent.com/89504211/132334995-1821673a-8a79-4426-98f0-02de2b006c1f.png)
![Screenshot from 2021-09-07 16-34-21](https://user-images.githubusercontent.com/89504211/132334999-2cb6b295-1726-4f41-b0b4-d8c24ef7b236.png)
![Screenshot from 2021-09-07 16-33-58](https://user-images.githubusercontent.com/89504211/132335008-7816ecfe-3236-47dd-8cb7-220b35fb658f.png)

**Comment by reddy95** [comment]
This issue is fixed
