### ISSUE TITLE
Handle data types for csvimport job

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#165]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngDesk-Data-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

In CSV import job few data types are being handled and few aren't, so should check for data types which are not handled and handle it, few data types observed which are not being handled are:
* Time
* dateTime
* date
* pickList(MultiSelecct)
* ListText
* Address
* phone field

**List of Steps:**

- [x] Handle all the above mentioned data types.
- [ ] Check for other data types which are not being handled and reachout to @karthikbalu1 for further approach.

**Test Criteria:**

- [ ] Test whether the value is stored for the data types which are being handled.

**Comment by abs-ravi** [comment]
**Completed:-**

- wrote code to handle address,list text and address field.


**Todo:-**

-  from csv file getting only phone no , for country flag and COUNTRY_CODE value need confirmation
- csvimports Api using Data proxy, date and date/time is handled already in data API, need confirmation

**Comment by abs-ravi** [comment]
**Completed:-**

- Tested the address field for csv imports its working fine.
- Wrote the code for handling the date,time,date/time and phone field.

**Todo:-**

- Need to test all data once the newly apis will be implemented on UI.


**Screenshots**

![Screenshot from 2021-09-10 12-08-53](https://user-images.githubusercontent.com/89505098/132841419-6f506cce-7605-43a8-ab96-ef068693631b.png)
![Screenshot from 2021-09-10 12-07-53](https://user-images.githubusercontent.com/89505098/132841425-271f2daa-a8b7-4aa3-bc99-743426700a0d.png)
![Screenshot from 2021-09-10 12-07-36](https://user-images.githubusercontent.com/89505098/132841427-bca2c9eb-bb05-4fc1-be52-6386aa6733fd.png)

**Comment by abs-ravi** [comment]
**Completed:-**

- were not able to generate APIS ,reached out to devops teams and get resolved
- created new branch keeping issue 99 as main.
- for headers for csvimports not getting proper payload from UI reported to @karthikbalu1 
- discuss all approach with @karthikbalu1  to handle all data type which all not handled yet.

**Todo:-**

- Getting few errors in dataservice waiting for changes of code of main branch for testing handled data fields
- waiting for requirements which all datatype fields need to handle


**Screenshots:-**
![image](https://user-images.githubusercontent.com/89505098/133080504-077fcdf2-28dd-4562-81bf-ec939cc85170.png)
