### ISSUE TITLE
BUG:Emails being null

### ISSUE THREAD

**Issue by vmirji** [SubscribeIT/ngDesk#230]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Manager

**Components/Services Affected (Ex. Login Component, POST Data API):**
- /ngDesk-Manager/src/main/java/com/ngdesk/jobs/Blacklist.java

**General Description/Overview:**

![Screenshot from 2021-10-06 08-53-07](https://user-images.githubusercontent.com/89504216/136135770-353b7fa8-39be-4020-9a05-f0e39b12a571.png)

**List of Steps:**
- [ ] Blacklist job, where ever we are sending email, make a get call to contact to fetch firstname and last name.

**Test Criteria:**
- [x] Emails must contain first name in the body section
- [x] Emails in dev environment doesnt work, use sysout to check

**Comment by vmirji** [comment]
Changes DOne
