### ISSUE TITLE
Email list improvements

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#235]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-rest, ngdesk-graphql

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

MIgrate the get/get all api calls for email list, from rest to graphql service.

**List of Steps:**
- [ ] Create data fetcher for email list.
- [ ] graphql query should be performed for email list.

**Test Criteria:**

- [ ] Email list populating properly.

**Comment by karthikbalu1** [comment]
Misunderstood requirement
