### ISSUE TITLE
Migrate Roles From Rest to Roles-Service

### ISSUE THREAD

**Issue by vmirji** [SubscribeIT/ngDesk#237]
**Owner:** @vmirji 

**Task Type:** 
- [ ] New 
- [x] Improvement 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- UI
- ngdesk-Rest
- ngdesk-Role Service
- ngdesk-Graphql

**General Description/Overview:**
Replace the old API calls with new ones. Graphql for get calls, and all the other calls with ngDesk-Role-Service calls.

**List of Steps:**
- [ ] Replace get calls with graphql calls
- [ ] Get create of Role working with new API
- [ ] Get update of Role working with new API
- [ ] Delete of Role working with new API
- [ ] Test all the APIs

**Test Criteria:**
- [ ] All the Graphql for get calls work
- [ ] All the ngDesk-Role-Service calls work
