### ISSUE TITLE
Internal error bug

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#27]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Data-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Validation.java

**General Description/Overview:**

![24](https://user-images.githubusercontent.com/89504119/130952872-7ffc0c23-ec07-423c-af80-e6f4f28e3d19.png)

**List of Steps:**
- [ ] Use Optional to get the user, check if the user is empty
- [ ] If user is empty, return

**Test Criteria:**
- [ ] Delete call working for other users other than one who is logged in

**Comment by arepallipriyanka** [comment]
issue already fixed, close issue.
