### ISSUE TITLE
Dashboard save bug

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#273]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-SAM
**Components/Services Affected (Ex. Login Component, POST Data API):**
- DashboardAPI

**General Description/Overview:**

![image](https://user-images.githubusercontent.com/89503138/139381552-b3e13b0a-8dee-4963-8d97-341677d2f6e3.png)

**List of Steps:**
- [ ] Current dashboard must not be checked if the dashboard is being edited

**Test Criteria:**
- [ ] Dashboard must save, it must not check other role dashboards and it self when editing
- [ ] Dashboard name must be unique for a role
