### ISSUE TITLE
sidbar improvement

### ISSUE THREAD

**Issue by ceanugula** [SubscribeIT/ngDesk#287]
**Owner:** @ceanugula 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngDesk-Company-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**
SidebarService

**General Description/Overview:**

We want to make sidebar dynamic based on the plugins selected by the user.

**List of Steps:**

- [x]  Create a json file add the side bar menu items for all the roles, with all the default modules.
 - [x] In sidbar service we have a function called post default sidebar, in that function fetch this json fine, loop through roles and 
      modules and replace role id's and module ids.
- [x]  Get all the plugins added by the user, loop through them and based on the plugin name retain the menu items and remove 
       the menu items which are not matched with the plugin name.
- [x] Convert the file contents to side bar object using object mapper, then  retain the required menu items and remove the 
      unwanted menu items based on the plugins.

**Test Criteria:**

- [x] Post a new company. 
- [x] Make sure side bar loads properly and check that it is adding only the modules present in the plugins added by the user.
- [x] Test it thoroughly and make sure everything works

**Comment by ceanugula** [comment]
* Added a json file called sidebar,json
* Modified postDefaultSidebar function in order to post side bar menu items based on the plugins selected by the user(only for system admin role, for other roles system admin can add).
* Tickets and pager will be posted by default.
* If user selects chats it will be added for both system admin and agents by default.
* Changed plugin name "Software Asset Management" to "SAM"
* Everything is working fine.

**Comment by reddy95** [comment]
### interchange the order :  while interchange the order of sidebar menus getting error like "MENU_ITEM_PATH_PARAMETER should not be null" 

- steps
- login to dev1 with system admin credentials 
- try to post a company with 3 or more plugins
- go to Sidebar Customization and try to add new menu and interchange the order of side bar menu list 
- observe the errror "MENU_ITEM_PATH_PARAMETER should not be null"


![image](https://user-images.githubusercontent.com/89504578/143175001-83bc5e50-8782-4a73-959f-c2f6ac962fef.png)

**Comment by ceanugula** [comment]
1. Issue resolved, It is not because of adding 3 or more plugins.
2. It is because path parameter is missing in "SAM" sidebar menu and path parameter is a required field.
3. Fixed one more issue also, for "SAM" menu, contracts was also added because of that it was throwing "module already 
    present in the sidebar", so i removed that, its working fine now.

![Screenshot from 2021-11-24 10-54-05](https://user-images.githubusercontent.com/89504492/143180337-484788f6-1e23-483a-8bbc-d7ecd4ed8c33.png)

**Comment by skumarls** [comment]
Removed applications, discovered software,licenses from SAM side bar menu in sidebar json file.

**Comment by reddy95** [comment]
issue is fixed

**Comment by sharath-satish** [comment]
PR is not linked, I have added comment in PR check it

**Comment by ceanugula** [comment]
* resolved issue mentioned in the pull request
* moved chats next to tickets

**Comment by ceanugula** [comment]
* resolved issues.
* added sidebar json file for each role.
* modified postDefaultSidebar function accordingly.
