### ISSUE TITLE
Migrate get and get all api for campaigns.

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#289]
**Owner:** @karthikbalu1 

**Task Type:** 
- [x] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-graphql

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

data fetchers should be created for campaigns.

**List of Steps:**

- [ ] Create get by id, data fetcher for campaign.
- [ ] Create get all, data fetcher for campaign.
- [ ] Create count fetcher for campaign.

**Test Criteria:**

- [ ] Test all the data fetcher created, check the response.

**Comment by skatapady** [comment]
as per discussion with @sharath-satish issue is on-hold.
