### ISSUE TITLE
New

### ISSUE THREAD

**Issue by ssanjay-22** [SubscribeIT/ngDesk#297]
**Owner:** @sharath-satish 

**Task Type:** 
- [x] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

- ngdesk-ui Notifications

**Components/Services Affected (Ex. Login Component, POST Data API):**

- Notification API 

**General Description/Overview:**

-  Create A New API to Read all the previous Notifications Related to the Recipient, Module and the Entry if User clicks on the Latest Notification
- if there is no previous notifications matching the criteria it should make only make that perticular notification as read

As a TYPE_OF_USER_OR_ROLE, I want SOME_GOAL so that SOME_REASON_OR_BENEFIT.

**List of Steps:**

- [ ] Create a notification API 

**Test Criteria:**

 

- [ ] if User Clicks on the latest notification it should make all the Related previous notifications as read 
- [ ]  if there is no previous notifications, Make the current one as read
