### ISSUE TITLE
Chat Prompts

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#314]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

* Handling Chat prompt.

**List of Steps:**

**Test Criteria:**

**Comment by skatapady** [comment]
- [ ] 2. **Create/ Edit Chat Prompts** - Chat prompts are saved or updated without selecting any Actions.

1. post a company with chats plugin and login with valid admin user credentials
2. click on modules --> chat --> channels --> Chats --> Prompts --> new button.
3. enter valid name and description.
4. let the conditions be empty
5. let the actions be empty
6. click on the save button.

We expect at-least one Action to be present before saving the prompts.

**Screenshot**

![Screenshot from 2022-01-24 17-04-08](https://user-images.githubusercontent.com/89504195/150775789-60035a3b-d400-4039-845d-82acfa8cf170.png)

**Comment by skatapady** [comment]
- [ ] 3. **Create/ Edit Chat Prompts** - Time in minutes for fields value should be validated for minimum and maximum length.

1. post a company with chats plugin and login with valid admin user credentials
2. click on modules --> chat --> channels --> Chats --> Prompts --> new button.
3. enter valid name and description.
4. click on the plus icon for meet all conditions
5. select conditions as 'still on site' or 'still on page'
6. enter value as '999999999999999'
7. select any action and text
8. click on the save button.

no validation is performed for field length. As it is in minutes, we expect validation in this case.

**Screenshot**

![Screenshot from 2022-01-24 17-13-00](https://user-images.githubusercontent.com/89504195/150777053-b6de0e8c-0ace-4281-ad84-567c4045cf4e.png)

![Screenshot from 2022-01-24 17-10-19](https://user-images.githubusercontent.com/89504195/150777060-f3e4cb46-5191-444c-95e0-0e7127124fdc.png)

![Screenshot from 2022-01-24 17-10-09](https://user-images.githubusercontent.com/89504195/150777070-e4c942a0-cfe7-47f1-8020-0f3d836cdfd2.png)

**Comment by skatapady** [comment]
- [ ] 4. **Chat Prompts** - Data is not sorting in the list layout.

**Steps:**

1. post a company with chats plugin and login with valid admin user credentials
2. click on modules --> chat --> channels --> Chats --> Prompts --> new button.
3. enter valid name and description.
4. select any action and text
5. click on the save button. (create 8 or 11 records)
6. click on the column header 'Prompt Name' in the list layout. (we expected data  to be sorted in ascending or descending order.)

Data is not sorted.

**Screenshot**

![Screenshot from 2022-01-24 17-20-30](https://user-images.githubusercontent.com/89504195/150777995-9001245c-4eb8-4851-8f38-81ade9b6ebb8.png)
![Screenshot from 2022-01-24 17-20-27](https://user-images.githubusercontent.com/89504195/150777999-a82ae828-5781-4798-8527-a42ffecca035.png)

**Comment by skatapady** [comment]
re opening the issue due to point mentioned in 2,3 & 4.

**Comment by skatapady** [comment]
- [ ] 5. Issue mentioned in point 3 is not fixed when we enter following value in text value field.
9999999999

Issue is also observed for **Hour of Day, Still on Site and Still on page** field.

**Screenshot**

![Screenshot from 2022-01-27 16-02-18](https://user-images.githubusercontent.com/89504195/151341996-91b7d4cb-4793-4a95-8192-a0db9c3e5ee6.png)

![Screenshot from 2022-01-27 16-00-27](https://user-images.githubusercontent.com/89504195/151341890-b5c77d85-ea8f-4cfe-97d4-53cc5f970719.png)

![Screenshot from 2022-01-27 16-00-13](https://user-images.githubusercontent.com/89504195/151341900-5d33e038-1154-4785-8f7c-dab34cf9ba31.png)

![Screenshot from 2022-01-27 16-00-09](https://user-images.githubusercontent.com/89504195/151341908-56db662a-2cdf-4f96-a2cc-21a5ed25392f.png)

![Screenshot from 2022-01-27 15-59-53](https://user-images.githubusercontent.com/89504195/151341917-7eb8da3e-a86b-4a07-8364-f7e5c1b63c4d.png)

**Comment by skatapady** [comment]
Re opening the issue due to issue mentioned in point 5

**Comment by knramya** [comment]
* issue number 5 is fixed

**Comment by skatapady** [comment]
issue mentioned in point 5 is fixed.
