### ISSUE TITLE
SLAs

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#32]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- SLA detail

**General Description/Overview:**

**List of Steps:**
- [x] Implement infinite scroll for workflow dropdown in the SLA detail
- [x] Have a link to workflow in sla edit layout to navigate the user to the workflow

**Test Criteria:**
- [x] Link to SLA working
- [x] Infinite scroll on the SLA create and edit layout workflows dropdown working

**Comment by spdhage** [comment]
This **issue** is **fixed**
