### ISSUE TITLE
Currency task

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#35]
**Owner:** @ssatish 

**Task Type:** 
- [x] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Render detail layouts

**General Description/Overview:**

As a User, I want to calculate currency so that I can use different currencies.

- CurrencyFields include TRANSACTION_DATE, FROM_CURRENCY, TO CURRENCY, BASE_VALUE, CONVERSION_VALUE

**List of Steps:**
- [ ] All these fields will be grouped by the group id
- [ ] When we select TRANSACTION_DATE, FROM_CURRENCY, TO_CURRENCY, BASE_VALUE we need to convert the value and populate it in CONVERTION_VALUE
- [ ] The currency conversion API can be used for the conversion(API is under module service)
- [ ] Add a change detection for all the fields

**Test Criteria:**
- [ ] The changes has to be converted and stored in the CONVERSION_VALUE field
- [ ] There must not be any null pointer error
