### ISSUE TITLE
Getting started progress tracking improvement

### ISSUE THREAD

**Issue by dharanids** [SubscribeIT/ngDesk#38]
**Owner:** @phaneendra.ar 

**Task Type:** 
- [ ] New 
- [x] Improvement 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
 - UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- getting-started component

**General Description/Overview:**

We need improvement on getting started progress tracking, it's not responsive enough to track progress, as soon as user does an action it should be reflected on the progress tracker

**List of Steps:**
1. Step 1
- [x] On load of the page, Personalize your ngdesk  is the first page but it doesn't show up as the current step
- [x] On save of the customization and success response the progress should be updated
- [x] if the user customizes from Company setting that also needs to update progress tacker

2. Step 2
- [x] Discuss with Phaneendra about this

3. Step 3 
- [x] On save of support email and success response the progress should be updated
- [x] if the user saves from module- tickets channel setting also needs to update progress tacker

4. Step 4 
- [x] On click of invite and success response progress should be updated
- [x] if the user invites from company settings that also needs to update progress tacker
- [x] after being complete the user is not able to go the invite page in getting started, this should be accessable

**Test Criteria:**
- [x] Test if all progress tracking steps are responsive

**Comment by AyushAllBlue** [comment]
Done :- 

- Worked on progress of spinner on customization save.
- Worked on progress of spinner on support email save.
- Worked on progress of spinner on invite user save.
- Worked on getting started progress on toolbar.

Pending :- 

- Need to work on progress of spinner on activate email save.
- Need to format the code.
- Need to test properly.

**Comment by AyushAllBlue** [comment]
Done :- 

- Worked on progress tracking function.
- Able to show proper progress after customization , support email, and invite user save.
- Tested progress in different scenarios.

Pending :- 

- Need to work on Activate email progress.
- Need to work on getting started progess in toolbar.

**Comment by AyushAllBlue** [comment]
Done :- 

- Worked on getting started progress in toolbar.
- Tested the getting started progress by completing different steps.

Pending :- 

- Need to work on Activate email progress.
- Need to test thoroughly.

**Comment by AyushAllBlue** [comment]
Done :- 

- Tried fixing the progress spinner in mozilla.
- Tried changing the style of spinner.

Pending :- 

- Need to figure out a way to fix progress spinner in mozilla.

**Comment by AyushAllBlue** [comment]
Done :- 

- Able to fix the progress bar in firefox.
- Tested the progress bar in both the browsers.

Pending :- 

- Need to fix the progress bar for safari and test it.

**Comment by unagireddy** [comment]
Testcase 1,2,3,4,5 are tested.Followed the steps 
1.Posted a new company. clicked on progress.and observed the progress bar.
2.Same thing observe when done from company settings customization.no error observed.
3.Clicked on activate email. and observed whether its moving to next step with no error
4.Clicked on Set up support email. and setup for internal and external and save and observed progress bar.5.
5.Same thing observe when done from company modules channels
6.Goto getting started.Observe the progress bar in chrome,firefox and safari
