### ISSUE TITLE
navigate back to escalations if create schedule was triggered from escalations page

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#39]
**Owner:** @phaneendra.ar 

**Task Type:** 
- [ ] New 
- [x] Improvement 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- escalations-detail component 
- schedules-detail component
- app-routing

**General Description/Overview:**

navigate back to escalations if create schedule was triggered from escalations page, this should work on both new escalation detail and existing escalation detail

![Screenshot from 2021-08-26 16-22-05](https://user-images.githubusercontent.com/89504211/130950704-637b82a7-26fc-410f-bba5-f4c248fceeb5.png)

**List of Steps:**

- [x] On click of create new schedule navigate to create schedule with the escalation Id
- [x] On save of schedule, navigate the user back to the same escalation 

**Test Criteria:**

- [x] test with multiple scenarios of the navigation to and fro from the escalations and schedules

**Comment by kkumar1995** [comment]
#### Reference to issue #39

Closes #39

#### Description (Required)

navigate back to escalations if create schedule was triggered from escalations page

##### Test Case 1

**Name:For create escalations**

1.Click on escalations under pager in side bar
2.Click on new->click on create new schedules
3.Page navigate to schedules and enter required details->click on save button
4.Observe page is return back to escalations create page


##### Test Case 2

**Name:For edit escalations**

1.Click on escalations under pager in side bar
2.Click on saved entry 
3.Click on create new schedules
4.Page navigate to schedules and enter required details->click on save button
5.Observe page is return back to escalations edit page


#### List of General Components affected (Required)

EscalationsDetailComponent,SchedulesDetailComponent

**screen-shots**

For create Escalations

![create1](https://user-images.githubusercontent.com/89504408/132274964-053d0d7d-d5e9-41fa-8977-6b1b2fdb0b4b.png)
![create2](https://user-images.githubusercontent.com/89504408/132274965-f6246615-1509-4535-9190-9e5b54af1629.png)
![create3](https://user-images.githubusercontent.com/89504408/132274973-5183d2d3-3c35-4605-a8e3-2b8d200146a0.png)
![create4](https://user-images.githubusercontent.com/89504408/132274981-2e510c5d-a479-46b1-ac6b-c607539d041c.png)
![create5](https://user-images.githubusercontent.com/89504408/132275015-e8cbeacb-57cb-40c5-960a-f23bdcf2e86b.png)
![create6](https://user-images.githubusercontent.com/89504408/132275023-b6cf2a8e-4b0e-4525-8501-a481b9639bc3.png)

For edit Escalations

![edit1](https://user-images.githubusercontent.com/89504408/132275045-64ecb3f2-8e0f-42d8-9a4e-e9e3003b06d4.png)
![edit2](https://user-images.githubusercontent.com/89504408/132275056-f1d50797-cee0-44ef-bb1a-f4c1795a2146.png)
![edit3](https://user-images.githubusercontent.com/89504408/132275062-e02f719a-bec8-4593-bbaa-b70c51cb85df.png)
![edit4](https://user-images.githubusercontent.com/89504408/132275068-50149d4a-a6ed-4379-bc2b-dac1b019e1f6.png)
![edit6](https://user-images.githubusercontent.com/89504408/132275076-23a783b8-3dcf-4c18-8ded-dbd2b2bfc4e5.png)
![edit7](https://user-images.githubusercontent.com/89504408/132275090-66ca94fe-cfee-43cb-ab6e-77f77ac2240e.png)

**Comment by kkumar1995** [comment]
issue is fixed and tested
