### ISSUE TITLE
add receipt attached field to expenses

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#5]
**Owner:** @ceanugula 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

ngDesk-Company-Service

ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

ExpensesModule.json
conditions component

**General Description/Overview:**
We need to add a new field called "Receipt Attached",add it to the list layouts and update it using a workflow.

**List of Steps:**

- [ ] Add a new field of type boolean ,called "Receipt Attached" to expenses module.
- [ ] Add it to the list layouts.
- [ ] Don't add it to create and edit layouts.
- [ ] Handle for receipt capture type in the ui.
- [ ] If necessary handle it in backend too
- [ ] Add a workflow, so that it will update the field, whenever a receipt is attached. 

**Test Criteria:**

- [ ] Post a new company and check whether that field is added to fields or not and also check on the list layouts.
- [ ] Check if workflow is added.
- [ ] Test by attaching a receipt.
