### ISSUE TITLE
Module template - Products

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#53]
**Owner:** @npanicker 

**Task Type:** 
- [x] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

will be done on production `ngdesk-crm.ngdesk.com`

**Components/Services Affected (Ex. Login Component, POST Data API):**

Products module in CRM subdomain

**General Description/Overview:**

Make changes for Products module fields and layouts on production ngdesk-crm subdomain.

**List of Steps:**

**Any changes to fields, if it is necessary to create a new field, append `new` to the name of the field so we know which to keep**

- [x] Rename `Tax Rate` to `Default Tax Rate` which will be a currency
- [x] Remove `Taxable` and `Service` checkboxes
- [x] Add list of worldwide currencies for `Currency` picklist using the file attached:

[Worldwide_currencies.txt](https://github.com/SubscribeIT/ngDesk/files/7058460/Worldwide_currencies.txt)

- [x] Rename `Product Number` to `Product Code`

**AT NO TIME SHOULD THIS SUBDOMAIN BE DELETED**

**Test Criteria:**

1. New changes to layouts and fields of Products module should reflect
2. Screenshots of layouts required
