### ISSUE TITLE
Add Cash Advance

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#6]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Company-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Expense Module.json, Expense Report.json

**General Description/Overview:**

As a User, I want Cash Advance to be shown in ngDesk.

![9](https://user-images.githubusercontent.com/89504119/130951353-5617ed0c-e46a-40d4-be7c-5edef211a71b.png)
![10](https://user-images.githubusercontent.com/89504119/130951358-1c883f98-f182-4c0d-8188-3ca23c167f10.png)

**List of Steps:**
- [x] Add a new option to payment type called as **Cash Advance** (Expense Module, Payment Type field)
- [x] Add Condition on the Cash Advance Remaining -> Payment Type - Equals To - Cash Advance

**Test Criteria:**
- [x] Post a new company with the expenses, and observe the fields updated
- [x] Post a new data to expenses and expense reports validate the data

**Comment by sharath-satish** [comment]
Merged in gitlab
