### ISSUE TITLE
schedules ui improvements

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#7]
**Owner:** @ceanugula 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
  ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

  schedule-detail-component

**General Description/Overview:**
  UI improvements

![11](https://user-images.githubusercontent.com/89504119/130951472-2de8811f-06ff-4e45-92a1-cb254d774984.png)

**List of Steps:**

- [x] Add a tool tip for each step, so that users can understand what they can do in each step.
- [x] Adjust the alignment in restrictions

**Test Criteria:**

- [x] Test by loading the detail page
