### ISSUE TITLE
Find agent and assign node

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#85]
#### Task Overview (Required)

**Find agent and assign node**

#### Ordered List of Steps to Complete the Task (Required)

- [ ] Find agent and assign node
- [ ] Find agent will find the agent from the redis queue and assign it to chat
- [ ] The widget is notified about the assigned user
- [ ] Meta data is sent to say which user joined the chat

#### Acceptance Criteria (Required)

- [] Find agent and assign node fetching the users who accept chat

#### Location in Project (Location in Code) (Recommended)

- TBD with spencer

#### Relevant screenshots or mock up

(Paste any mock or screenshot)
