### ISSUE TITLE
Migrate CSV Import to latest code

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#99]
**Owner:** @sharath-satish 
**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-data, ngdesk-graphql, ngdesk-rest, ngdesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**
WIth the csv and excel format file, the entry should be imported.

**List of Steps:**

- [x] Migrate csv import job from rest to data service
- [x] Handled in graphql for get api's
- [x] Handle the UI for showing import dialog box and display import logs.

**Test Criteria:**

- [ ] Should be able to import entries via csv/excel files.

**Comment by karthikbalu1** [comment]
Requirement update:
- Should migrate CSV import to data service.
- The get api calls should be performed using graphql.

**Comment by apriya22** [comment]
Completed

* Api integration for csv imports
* added api call to display all the imports
* added post call for csv imports
* 
![Screenshot from 2021-09-08 16-33-36](https://user-images.githubusercontent.com/89504219/132503338-4c43e4dd-1cd5-4d60-a65b-383b5f117c55.png)
![Screenshot from 2021-09-08 16-33-55](https://user-images.githubusercontent.com/89504219/132503345-0d9c9466-abfd-408b-a4ac-2feeb3765260.png)
![Screenshot from 2021-09-08 16-34-24](https://user-images.githubusercontent.com/89504219/132503348-a7e61a75-abb2-4b7b-b8a4-c4f109c990d2.png)


Todo

* status of imports doent change in master component 
* Testing
* If any changes in BE is done , then Fe need to be updated

**Comment by apriya22** [comment]
Completed

* fixed the master component 
*  worked on detail layout of CSV import 
   - added API call
 * All the frontend changes are done
 
![Screenshot from 2021-09-09 16-14-25](https://user-images.githubusercontent.com/89504219/132679544-fd88d981-5075-40f7-8b36-4be73826587f.png)
![Screenshot from 2021-09-09 16-14-30](https://user-images.githubusercontent.com/89504219/132679561-c14b1f6f-f9ab-4b07-9543-177df80b24f6.png)

**Comment by apriya22** [comment]
COMPLETED

* trying to add separator when the user selects phone field.

TODO

* Separator should display when phone field is selected

**Comment by apriya22** [comment]
COMPLETED

* added separator in phone field 
![Screenshot from 2021-09-15 16-54-48](https://user-images.githubusercontent.com/89504219/133425836-cf900b42-1961-4b74-abd3-0ae7b421626d.png)
![Screenshot from 2021-09-15 16-54-55](https://user-images.githubusercontent.com/89504219/133425844-11ccc101-d478-4683-83cc-3cfaa4fc6cb7.png)

**Comment by apriya22** [comment]
Completed

* tried different style still its ot aliginment isnt proper 
* trying flex and working

TODO

* logs detail page is not aligned properly. imports

**Comment by apriya22** [comment]
COmpleted

* fixed the alignment  of logs detail page
* 
![Screenshot from 2021-09-23 13-05-20](https://user-images.githubusercontent.com/89504219/134500005-a5543c0a-004f-4e2d-9695-c79c5fc57353.png)
![Screenshot from 2021-09-23 13-05-30](https://user-images.githubusercontent.com/89504219/134500017-fb02a9bd-ca0d-483d-8ea1-b54ca0c779ed.png)
![Screenshot from 2021-09-23 13-05-42](https://user-images.githubusercontent.com/89504219/134500026-96ea4270-b186-4c67-b80d-e044ad248bf1.png)

**Comment by apriya22** [comment]
Completed

* fixed the alignment of phone field
* 
![Screenshot from 2021-09-27 16-03-04](https://user-images.githubusercontent.com/89504219/134901482-4338f44c-b33e-403c-8876-0543549dd264.png)

**Comment by apriya22** [comment]
Completed

* Added date format list for a date, date/time, and time field

![Screenshot from 2021-09-29 15-24-54](https://user-images.githubusercontent.com/89504219/135281130-2bcf6f02-e068-4726-8766-04036b30c3d4.png)

TODO

* need to hook it up with the backend
*  save should work properly

**Comment by apriya22** [comment]
Completed

* hooked up with the backend
* Save it

![Screenshot from 2021-09-30 17-10-23](https://user-images.githubusercontent.com/89504219/135449238-77ccf27a-392a-41e0-924a-2d32e9f7da45.png)
![Screenshot from 2021-09-30 17-10-33](https://user-images.githubusercontent.com/89504219/135449248-6b33b3fe-4ddd-468b-9386-7244616d1425.png)
![Screenshot from 2021-09-30 17-10-50](https://user-images.githubusercontent.com/89504219/135449251-6894c031-6a2d-421e-b6dd-4707a7f43828.png)

**Comment by apriya22** [comment]
DONE

* change the design to display to format for date, date/time, time and phone field
* 
![Screenshot from 2021-10-01 16-54-53](https://user-images.githubusercontent.com/89504219/135612757-8cfb7691-1c24-4d3b-a6b2-3bb4faf30046.png)
![Screenshot from 2021-10-01 16-55-51](https://user-images.githubusercontent.com/89504219/135612763-bb726ab2-dc28-4ae0-99a7-7289304da110.png)
![Screenshot from 2021-10-01 16-55-55](https://user-images.githubusercontent.com/89504219/135612769-8a9f3fa4-646f-4f60-80b6-33645d4a5d43.png)
![Screenshot from 2021-10-01 16-56-47](https://user-images.githubusercontent.com/89504219/135612772-83b794bc-3c7b-4e6d-bdb3-f698d3ebaca7.png)

**Comment by apriya22** [comment]
COMPLETED

* working on CSV detail page
* working on click of lines failed table should display 

TODO

* table should display on click no of lines completed

**Comment by apriya22** [comment]
Completed

* improvements done in detail page for CSV imports

TODO

* hookup with backend call.

**Comment by apriya22** [comment]
Completed
* hooked up with grapql call
* logs tables displaying on click of lines failed
![Screenshot from 2021-10-12 15-37-19](https://user-images.githubusercontent.com/89504219/136950181-652d9bc9-b46a-4b8e-8e07-f32f255f2472.png)
![Screenshot from 2021-10-12 15-37-21](https://user-images.githubusercontent.com/89504219/136950186-2fc7ec47-c393-434b-958e-bf5fb3769306.png)

**Comment by unagireddy** [comment]
Test case 1,2 got tested  and followed the steps
posted a new company. and open one module and created fields with all the data types. and added them to the edit and create layout.
opened the import module form data fille in company settings 
Selected module to import and added csv file and added all related fileds for csv import like phone:PHONEFILED , email:EMAIl
etc. And clicked on import .
A new file will be imported and checked with the corresponding module whether the updated entries are cretaed or not 
for example of i selected a ticket in import module and ticket.csv file in csv file 
new tickets will be generated in the ticket which is present on sidebar like csv file 41,csv file 42, csvfile 43
Like vise i have tested  all the modules 
for 2nd testcase
I have created a custom module. and created fields with all the data types and add all them to create and  edit layout and aded same module to the side bar
followed same steps as above 
once the file is imported and it is completed open the newly added module in the sidebar except the chronometer value.
tested all the conditions
/spend 10hrs
.


![image](https://user-images.githubusercontent.com/89505057/141927446-443f760b-056d-43fb-b5b6-10d6a45788ed.png)

![image](https://user-images.githubusercontent.com/89505057/141927514-8ca3009d-4ecf-48ce-af5d-633d551365a2.png)
![image](https://user-images.githubusercontent.com/89505057/141927645-742ded2f-ff54-40c4-b1ab-eaf8e0d8bb5b.png)

![image](https://user-images.githubusercontent.com/89505057/141927725-b383fc0d-08dc-459e-8519-05e389de73d4.png)
